import Head from "next/head";
import Image from "next/image";
import Slider from "../components/Slider";
import styles from "../styles/Home.module.css";

export default function Home({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Slider data={data} />
    </div>
  );
}

export async function getServerSideProps(context) {
  const resp = await fetch(`https://yts.mx/api/v2/list_movies.json?page=${1}`);
  const respData = await resp.json();
  const data = respData.data.movies;

  // setMovies(data);

  //   setlength(data.length);
  //   setCount(respData.data.movie_count);
  //   setMovies(Movies.concat(data));
  //   setPage(Page + 1);
  return {
    props: { data }, // will be passed to the page component as props
  };
}
